import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Devbridge",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0a0a0a] py-12 px-4">
      <div className="max-w-2xl mx-auto">
        <Link href="/" className="text-[#555] text-sm hover:text-[#E8A838] transition mb-8 block">
          ← Back to Home
        </Link>

        <h1 className="font-crimson text-4xl text-white mb-2">Terms of Service</h1>
        <p className="text-[#555] text-sm mb-10">Last updated: May 2025</p>

        <div className="space-y-8 text-[#888] text-sm leading-relaxed">
          <section>
            <h2 className="text-white text-lg font-semibold mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Devbridge's services, you agree to be bound by these Terms of
              Service. If you do not agree, do not use the service. These terms apply to all visitors,
              users, and founders who access or use the platform.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-3">2. Description of Service</h2>
            <p>
              Devbridge provides AI-powered startup evaluation tools including:
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Founder Readiness Check — 70-question readiness assessment</li>
              <li>Startup Viability Advisor — Intake-based advisory evaluation</li>
              <li>Pitch Deck Validator — Document-based pitch deck analysis</li>
            </ul>
            <p className="mt-3">
              All evaluations are AI-generated and provided for informational and educational
              purposes only. They do not constitute legal, financial, or investment advice.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-3">3. Payment Terms</h2>
            <p>
              A one-time payment of <strong className="text-[#aaa]">₹999 (Indian Rupees)</strong> is
              required for each report generation. This includes:
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Each initial report generation</li>
              <li>Each re-generation or retry</li>
              <li>Each separate service (readiness check, advisor, pitch deck — billed separately)</li>
            </ul>
            <p className="mt-3">
              Payments are non-refundable once a report has been successfully generated. See our
              Refund Policy for exceptions.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-3">4. No Guarantee of Accuracy</h2>
            <p>
              Devbridge's evaluations are generated by AI models and may contain errors, omissions, or
              assessments that do not reflect your actual business viability. Reports are a starting
              point for thinking — not a definitive verdict. Devbridge makes no warranties about the
              accuracy, completeness, or fitness for any particular purpose of the reports generated.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-3">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Submit false, misleading, or harmful content in your answers or uploads.</li>
              <li>Attempt to reverse-engineer, scrape, or exploit the service.</li>
              <li>Use the service for any illegal purpose.</li>
              <li>Submit content that infringes third-party intellectual property rights.</li>
              <li>Attempt to circumvent payment requirements.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-3">6. Intellectual Property</h2>
            <p>
              The evaluation reports generated are provided to you for your personal and business use.
              You retain ownership of your input content. Devbridge retains all rights in its
              evaluation methodology, prompts, platform, and code.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-3">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Devbridge shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages arising from your use of the
              service. Our total liability for any claim shall not exceed the amount you paid for the
              specific report in question (₹999).
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-3">8. Data & Privacy</h2>
            <p>
              Your use of the service is also governed by our{" "}
              <Link href="/privacy-policy" className="text-[#E8A838] hover:underline">Privacy Policy</Link>,
              which is incorporated into these terms by reference.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-3">9. Modifications</h2>
            <p>
              We reserve the right to modify these terms at any time. Continued use of the service
              after changes constitutes acceptance. We will update the "Last updated" date at the top.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-3">10. Governing Law</h2>
            <p>
              These terms are governed by the laws of India. Any disputes shall be subject to the
              exclusive jurisdiction of courts in India.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-3">11. Contact</h2>
            <p>
              For questions about these terms, <Link href="/contact" className="text-[#E8A838] hover:underline">contact us here</Link>.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-[#1a1a1a] flex gap-4 text-xs text-[#444]">
          <Link href="/privacy-policy" className="hover:text-[#888] transition">Privacy Policy</Link>
          <Link href="/refund-policy" className="hover:text-[#888] transition">Refund Policy</Link>
          <Link href="/" className="hover:text-[#888] transition">Home</Link>
        </div>
      </div>
    </main>
  );
}
