import { NextRequest, NextResponse } from "next/server";
import { getReport, getSession } from "@/lib/db";
import { isAdminRequest } from "@/lib/admin-auth";

export async function GET(req: NextRequest) {
  const sessionId = req.nextUrl.searchParams.get("sessionId");
  if (!sessionId) return NextResponse.json({ error: "Missing sessionId" }, { status: 400 });

  const [report, session] = await Promise.all([getReport(sessionId), getSession(sessionId)]);
  if (!report || !session) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const isAdmin = isAdminRequest(req);

  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 190;
  let y = 20;

  const addLine = (text: string, size = 11, bold = false) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    const lines = doc.splitTextToSize(text, W);
    lines.forEach((line: string) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(line, 10, y);
      y += size * 0.5;
    });
    y += 3;
  };

  const addList = (items: string[] | undefined) => {
    if (!items?.length) return;
    items.forEach((item) => addLine(`• ${item}`));
  };

  const verdictColor: Record<string, [number, number, number]> = {
    "READY": [0, 160, 80],
    "CONDITIONALLY READY": [200, 140, 0],
    "NOT READY": [200, 0, 0],
  };
  const [r, g, b] = verdictColor[report.verdict] ?? [100, 100, 100];

  addLine("Founder Readiness Check", 18, true);
  addLine(`Founder: ${session.founderName}`, 12);
  if (session.startupType) addLine(`Type: ${session.startupType}`, 11);
  addLine(`Date: ${new Date(session.createdAt).toLocaleDateString()}`, 11);
  y += 5;

  doc.setTextColor(r, g, b);
  addLine(`Verdict: ${report.verdict}`, 14, true);
  doc.setTextColor(0, 0, 0);
  addLine(report.verdictExplanation, 11);
  y += 4;

  if (typeof report.realityScore === "number") {
    addLine(`Reality Score: ${report.realityScore}/100`, 12, true);
    y += 2;
  }

  addLine("What to Resolve Before Validation:", 13, true);
  addList(report.mustResolveBeforeValidation);
  y += 4;

  if (report.nextSteps?.length) {
    addLine("Recommended Next Steps:", 13, true);
    report.nextSteps.forEach((item, i) => addLine(`${i + 1}. ${item}`));
    y += 4;
  }

  addLine("Kill Signals to Watch:", 13, true);
  addList(report.killSignals);
  y += 4;

  addLine("Final Assessment:", 13, true);
  addLine(report.finalSummary);

  if (isAdmin) {
    y += 6;
    addLine("─── ADMIN VIEW ─────────────────────────", 10, true);

    if (typeof report.realityScore === "number") {
      addLine(`Reality Score: ${report.realityScore}/100`, 12, true);
    }

    if (report.phaseScores?.length) {
      addLine("Phase Scores:", 12, true);
      report.phaseScores.forEach((ps) => {
        addLine(`  Phase ${ps.phase} — ${ps.title}: ${ps.score}/10`);
        if (ps.note) addLine(`    ${ps.note}`, 10);
      });
      y += 2;
    }

    if (report.contradictions?.length) {
      addLine("Contradictions:", 12, true);
      addList(report.contradictions);
      y += 2;
    }

    addLine("Founder — Solid:", 12, true);
    addList(report.founderStressTest?.solid);
    addLine("Founder — Gaps:", 12, true);
    addList(report.founderStressTest?.gaps);
    addLine("Not Honest With Themselves About:", 12, true);
    addList(report.founderStressTest?.notHonestWith);

    addLine("Project — Coherent:", 12, true);
    addList(report.projectStressTest?.coherent);
    addLine("Project — Structural Weaknesses:", 12, true);
    addList(report.projectStressTest?.structuralWeaknesses);
    addLine("Unexamined Assumptions:", 12, true);
    addList(report.projectStressTest?.unexaminedAssumptions);

    addLine("What Founder Does Not Know:", 12, true);
    addList(report.whatFounderDoesNotKnow);
    addLine("Most Dangerous Assumptions:", 12, true);
    addList(report.mostDangerousAssumptions);
  }

  y += 8;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Founder Readiness Check. AI-generated — use as a thinking tool, not a final verdict.", 10, y);

  const pdfBytes = doc.output("arraybuffer");
  return new NextResponse(pdfBytes, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="readiness-report-${sessionId.slice(0, 8)}.pdf"`,
    },
  });
}
